spring:
  datasource:
    url: jdbc:h2:mem:library
    driver-class-name: org.h2.Driver
  liquibase:
    enabled: true
    contexts: dev
h2:
  console:
    path: /h2-console
    settings:
      web-allow-others: true
