spring:
  datasource:
    url: jdbc:h2:mem:library
    driver-class-name: org.h2.Driver
  liquibase:
    enabled: true
    contexts: dev
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
h2:
  console:
    path: /h2-console
    settings:
      web-allow-others: true
jpa-dao-enabled: true
book:
  out:
    comments:
      count: 2