spring:
  output.ansi.enabled: always
  profiles:
    active: fun
application:
  events:
    show-half-questions: false
  ask-questions-max-attempts: 3
  min-pass-count: 3
  localized-files:
    ru-RU: questions_ru.csv
    en-EN: questions_en.csv
  locale-name: ru-RU
  #locale: en-EN
---
application:
  profiles: fun
  events:
    show-half-questions: true
---
application:
  profiles: calm
  events:
    show-half-questions: true
---